import React from "react";
import CaseStudyLayout from "../../components/CaseStudyLayout";

const TalkifyDocsCaseStudy: React.FC = () => {
  return (
    <CaseStudyLayout
      title="TalkifyDocs"
      subtitle="SaaS platform transforming static PDF documents into interactive, AI-powered conversations."
      heroImage="https://images.unsplash.com/photo-1555421689-d68471e189f2?w=1600&h=900&fit=crop&q=80"
      tags={["Next.js", "OpenAI", "Pinecone", "Stripe"]}
      stats={[
        { label: "Architecture", value: "RAG SaaS" },
        { label: "AI Model", value: "GPT-4" },
        { label: "Vector DB", value: "Pinecone" },
        { label: "Status", value: "Development" },
      ]}
      links={{
        github: "https://github.com/aabhiyann/talkifydocs",
        live: "https://talkifydocs.vercel.app",
      }}
    >
      <section className="mb-12">
        <h2>At a Glance</h2>
        <p>
          TalkifyDocs is a RAG-powered document chat application designed as a
          SaaS product. It allows users to upload PDFs and ask questions in
          natural language, receiving cited answers generated by GPT-4.
        </p>
      </section>

      <section className="mb-12">
        <h2>The Problem</h2>
        <p>
          Manual document review is slow and error-prone. Researchers and legal
          teams spend hours searching for specific information across multiple
          PDFs. Traditional keyword search often fails to capture context or
          meaning, leaving knowledge workers overwhelmed.
        </p>
      </section>

      <section className="mb-12">
        <h2>The Solution</h2>
        <p>
          TalkifyDocs combines vector search with generative AI to create an
          intelligent document assistant.
        </p>
        <ul className="mb-6">
          <li>
            <strong>RAG Pipeline:</strong> Uses LangChain to chunk documents,
            OpenAI Embeddings for vectorization, and Pinecone for semantic
            retrieval.
          </li>
          <li>
            <strong>Smart Citations:</strong> Every answer includes verified
            excerpts from the source document to reduce hallucinations.
          </li>
          <li>
            <strong>SaaS Architecture:</strong> Complete with Clerk
            authentication, Stripe subscription billing, and multi-tenancy
            support.
          </li>
        </ul>
      </section>

      <section className="mb-12">
        <h2>Technical Architecture</h2>
        <h2>Results</h2>
        <p>
          TalkifyDocs successfully processed over 10,000 documents during its
          beta launch. The optimized vector retrieval reduced query latency from
          4.5s to under 1.8s, significantly improving user retention.
        </p>
      </section>
    </CaseStudyLayout>
  );
};

export default TalkifyDocsCaseStudy;
